### ISSUE TITLE
UnboundLocalError: local variable 'chrome_driver' referenced before assignment

### ISSUE THREAD

**Issue by dhavalsavalia** [Stormiix/pluralsight_scraper#1]
Error I'm getting

```
(pluralsight_scraper) $ python pluralsight.py
Traceback (most recent call last):
  File "pluralsight.py", line 14, in <module>
    course.launchBrowser()
  File "/Users/dhavalsavalia/Dev/Python/pluralsight_scraper/pluralsight_scraper/scraper.py", line 44, in launchBrowser
    self.browser = webdriver.Chrome(chrome_driver)
UnboundLocalError: local variable 'chrome_driver' referenced before assignment
```

I don't what wrong am I doing.

**Comment by 59adc5ed-4a64-4984-bf6a-2b9117da6625** [comment]
You need ChromeDriver for the actual scraping mechanism

``` python
 def launchBrowser(self):
        assert not self.browser, "Browser already set !"
        # Initiate the Browser webdriver
        currentfolder = os.path.dirname(os.path.abspath(inspect.stack()[0][1]))
        # Check which operating system is being used !
        if platform == "linux" or platform == "linux2":
            # linux
            chrome_driver = currentfolder+"/chromedriver"
        elif platform == "win32":
            # Windows
            chrome_driver = currentfolder+"/chromedriver.exe"
```

**You can find it here:**
https://sites.google.com/a/chromium.org/chromedriver/downloads

**Comment by Stormix** [comment]
The only cause I can think of to this issue is that he's using MacOS which I forgot about:
So the code should be:
```python
  def launchBrowser(self):
        assert not self.browser, "Browser already set !"
        # Initiate the Browser webdriver
        currentfolder = os.path.dirname(os.path.abspath(inspect.stack()[0][1]))
        # Check which operating system is being used !
        if platform == "linux" or platform == "linux2":
            # linux
            chrome_driver = currentfolder+"/chromedriver"
        elif platform == "win32":
            # Windows
            chrome_driver = currentfolder+"/chromedriver.exe"
		#The next lines should be added
		else: # Could of used an "elif" here
			# We'll assume it's mac os: platform == "darwin"
			# so download the mac binary : https://chromedriver.storage.googleapis.com/index.html?path=2.37/
			chrome_driver = currentfolder+"/chromedriver"
```
Download link for the current version (06-04-2018): [v2.37](https://chromedriver.storage.googleapis.com/index.html?path=2.37/)
Since I don't have access to any Mac system, please test this and let me know so I can push the changes.
