### ISSUE TITLE
Cannot find element (?)

### ISSUE THREAD

**Issue by dmaglio** [Stormiix/pluralsight_scraper#2]
```
Browser Initiated !
('Loading .. https://app.pluralsight.com/player?course=ng-big-picture&author=joe-eames&name=ef9637a3-aa5b-42cd-a068-bf216ba15a3d&clip=1&mode=live',)
✓
('Logging in ...',)
✓
<Download> folder created !
<Download/course-overview> folder created !
<Download/course-overview/course-overview> folder created !
('Downloading : ', 'course-overview.mp4')
[################################] 1148/1148 - 00:00:01
<Download/introduction> folder created !
<Download/introduction/introduction> folder created !
('Downloading : ', 'introduction.mp4')
[################################] 1148/1148 - 00:00:01
<Download/introduction/angular-what-and-why> folder created !
Traceback (most recent call last):
  File "pluralsight.py", line 16, in <module>
    log = course.downloadEpisodes()
  File "/home/davidemaglio/Scaricati/pluralsight_scraper/scraper.py", line 106, in downloadEpisodes
    self.browser.find_element_by_xpath("//*[contains(text(), '"+ModuleEpisodesList[j]+"')]").click()
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 309, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 787, in find_element
    'value': value})['value']
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[contains(text(), 'Angular, What, and Why')]"}
  (Session info: chrome=69.0.3497.81)
  (Driver info: chromedriver=2.38 (0),platform=Linux 4.17.19-200.fc28.x86_64 x86_64)
```

**Comment by Stormix** [comment]
Since I no longer have a Pluralsight subscriptions, I am no longer able to maintain this project, unless someone's ready to help with that. I'll go ahead and close this issue.
