### ISSUE TITLE
Missing Chrome Driver. 

### ISSUE THREAD

**Issue by da-musaddiq** [Stormiix/pluralsight_scraper#3]
C:\Users\USER\Desktop\pluralsight_scraper-master\pluralsight_scraper-master>pyth
on pluralsight.py
Traceback (most recent call last):
  File "C:\Python37-32\lib\site-packages\selenium\webdriver\common\service.py",
line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "C:\Python37-32\lib\subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "C:\Python37-32\lib\subprocess.py", line 1172, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pluralsight.py", line 14, in <module>
    course.launchBrowser()
  File "C:\Users\USER\Desktop\pluralsight_scraper-master\pluralsight_scraper-mas
ter\scraper.py", line 44, in launchBrowser
    self.browser = webdriver.Chrome(chrome_driver)
  File "C:\Python37-32\lib\site-packages\selenium\webdriver\chrome\webdriver.py"
, line 62, in __init__
    self.service.start()
  File "C:\Python37-32\lib\site-packages\selenium\webdriver\common\service.py",
line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' execu
table needs to be in PATH. Please see https://sites.google.com/a/chromium.org/ch
romedriver/home

C:\Users\USER\Desktop\pluralsight_scraper-master\pluralsight_scraper-master>

**Comment by Stormix** [comment]
This issue to the missing chrome Driver. Download it and add it to you Environment Path.
